# Uncomment this line to define a global platform for your project
# platform :ios, '9.2'
# Uncomment this line if you're using Swift
# use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'DGCars' do
    pod 'CocoaAsyncSocket'
    pod 'MJExtension'
end

target 'DGCarsTests' do

end

target 'DGCarsUITests' do

end

